Optilog/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from opti.admin import admin_site
from opti import views

urlpatterns = [
    path('admin/', admin_site.urls),
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('opti/', include("opti.urls")),    
]

opti/urls.py
from django.urls import path
from . import views

app_name = "opti"
urlpatterns = [
    path("", views.index, name="index"),
    path('optimization/', views.optimization_view, name='optimization_view'),
    path("detail/", views.detail, name="detail"),
    path("optimize/", views.optimize, name="optimize"),
]

opti/models.py
from django.db import models

# Create your models here.
class WeeklyTransportCapacity(models.Model):
    week_of_year = models.IntegerField()
    max_transport_capacity = models.FloatField(default=0)
    def __str__(self):
        return str(self.week_of_year)

class Slaugherhouse(models.Model):
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name

class Farm(models.Model):
    name = models.CharField(max_length=300)
    def __str__(self):
        return self.name

class WeeklyAnimalTransport(models.Model):
    origin_farm = models.ForeignKey(Farm, on_delete=models.DO_NOTHING)
    destination_slaughterhouse = models.ForeignKey(Slaugherhouse, on_delete=models.DO_NOTHING)
    transport_cost = models.FloatField(default=0)
    week_of_year = models.IntegerField()
    def __str__(self):
        return str(self.week_of_year) + '_' + self.origin_farm.name + '_' + self.destination_slaughterhouse.name

class WeeklySlaughterhouseDemand(models.Model):
    slaughterhouse = models.ForeignKey(Slaugherhouse, on_delete=models.DO_NOTHING)
    animal_count = models.IntegerField(default=0)
    live_animal_price_per_kg = models.FloatField(default=0)
    week_of_year = models.IntegerField()
    def __str__(self):
        return str(self.week_of_year) + '_' + self.slaughterhouse.name

class WeeklyFarmAnimalAvailability(models.Model):
    farm = models.ForeignKey(Farm, on_delete=models.DO_NOTHING)
    animal_count = models.IntegerField(default=0)
    average_weight = models.FloatField(default=0)
    week_of_year = models.IntegerField()
    def __str__(self):
        return str(self.week_of_year) + '_' + self.farm.name

opti/views.py
from django.contrib.admin.sites import site
from django.shortcuts import render
from django.urls import reverse

from .services.optimize_services import optimize_transport
from .services.weekly_transport_capacity_service import get_weeks_of_year_availables
from .services.weekly_transport_capacity_service import get_all_weekly_transport_capacity
from .services.weekly_animal_transport_service import get_all_weekly_animal_transport
from .services.weekly_slaughterhouse_demand_service import get_all_weekly_slaughterhouse_demand
from .services.weekly_farm_animal_avilability_service import get_all_weekly_farm_animal_availability

def index(request):
    return render(request, 'index.html')

def detail(request):
    list_week_of_year_available = get_weeks_of_year_availables()

    return render(request, "opti/detail.html", {"weeksOfYear": list_week_of_year_available})

def optimize(request):
    result = ""

    if request.method == 'POST':
        week_of_year_selected = request.POST.get('weekOfYear')
        result = optimize_transport(week_of_year_selected)

    list_week_of_year_available = get_weeks_of_year_availables()

    context = {
        'weeksOfYear': list_week_of_year_available,
        'result': result,
    }

    return render(request, "opti/detail.html", context)

def optimization_view(request, admin_site):
    error_message = None
    list_week_of_year_available = get_weeks_of_year_availables()
    week_of_year_selected = request.GET.get('week_of_year_selected')
    weekly_transport_capacity = get_all_weekly_transport_capacity()
    weekly_animal_transport = get_all_weekly_animal_transport()
    weekly_slaughterhouse_demand = get_all_weekly_slaughterhouse_demand()
    weekly_farm_animal_availability = get_all_weekly_farm_animal_availability()
    result = ''

    if 'action' in request.GET:
        action = request.GET['action']
        
        if action == 'optimize' and week_of_year_selected:
            result = optimize_transport(week_of_year_selected)
        else:
            result = ''

    if week_of_year_selected:
        weekly_transport_capacity = weekly_transport_capacity.filter(week_of_year=week_of_year_selected)
        weekly_animal_transport = weekly_animal_transport.filter(week_of_year=week_of_year_selected)
        weekly_slaughterhouse_demand = weekly_slaughterhouse_demand.filter(week_of_year=week_of_year_selected)
        weekly_farm_animal_availability = weekly_farm_animal_availability.filter(week_of_year=week_of_year_selected)
    
    breadcrumbs=[
            {'url': reverse('admin:index'), 'title': admin_site.site_header},
            {'url': reverse('admin:optimization_view'), 'title': 'Optimization'},
        ]

    context = admin_site.each_context(request)

    context.update({
        'weeks_of_year': list_week_of_year_available,
        'weekly_transport_capacity': weekly_transport_capacity,
        'weekly_animal_transport': weekly_animal_transport,
        'weekly_slaughterhouse_demand': weekly_slaughterhouse_demand,
        'weekly_farm_animal_availability': weekly_farm_animal_availability,
        'week_of_year_selected': week_of_year_selected,
        'error_message': error_message,
        'result': result,
        'breadcrumbs': breadcrumbs,
    })
    
    return render(request, 'admin/optimization_view.html', context)
    #return TemplateResponse(request, 'admin/optimization_view.html', context)

opti/templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Proyecto de Fin de Grado</title>
    {% load static %}
    <link href="{% static 'src/output.css' %}" rel="stylesheet">
</head>
<body class="bg-gray-100 text-gray-900 mx-auto p-4 sm:p-6 lg:p-8">
    <header class="bg-white shadow mb-6">
        <div class="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8 flex items-center justify-between">
            <div class="flex items-center">
                <img src="{% static 'images/unir_logo.png' %}" alt="Logo UNIR" class="h-10 w-auto">
            </div>
        </div>
    </header>
    <main class="max-w-7xl mx-auto py-10 px-4 sm:px-6 lg:px-8">
        <div class="bg-white shadow overflow-hidden sm:rounded-lg">
            <div class="px-4 py-5 sm:px-6">
                <h1 class="text-3xl leading-6 font-bold text-gray-900">Bienvenido al Proyecto de Fin de Grado</h1>
                <p class="mt-1 max-w-2xl text-sm text-gray-500">Inicia sesión para acceder al contenido.</p>
                <div class="mt-4">
                    <a href="{% url 'admin:index' %}" class="button">
                        Admin
                    </a>
                </div>
            </div>
        </div>
    </main>
</body>
</html>

opti/templates/opti/detail.html
<h1>Optimization</h1>
<form action='{% url 'opti:optimize' %}' method="POST">
    {% csrf_token %}
    <fieldset>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        <select name="weekOfYear" id="weekOfYear">
            {% for week in weeksOfYear %}
                <option value="{{ week }}">{{ week }}</option>
            {% endfor %}
        </select>
    </fieldset>
    <input type="submit" value="Optimize">
</form>
<div>
    <h2>Resultado</h2>
    <pre>{{ result }}</pre>
</div>